CREATE TABLE [dbo].[DIARIO1]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	[NOME] VARCHAR(100) NOT NULL,
	[MATERIA] VARCHAR(50) NOT NULL,
	[NOTA1] INT NOT NULL,
	[NOTA2] INT NOT NULL,
	[NOTA3] INT NOT NULL,
	[NOTA4] INT NOT NULL,
	[NOTA5] INT NOT NULL,
	[NOTA6] INT NOT NULL,
	[MEDIA] AS ((NOTA1 + NOTA2 + NOTA3 + NOTA4 + NOTA5 + NOTA6)/ 6),
	[STATUS] AS IIF(((NOTA1 + NOTA2 + NOTA3 + NOTA4 + NOTA5 + NOTA6)/ 6) >= 5,'APROVADO','REPROVADO')
)
